/* This file should be replaced by the file generated by the binarization process */

#include "Precomp.h"
#include "MATHs/MATHvector_aligned.h"
#include "AI2C_fctheader.h"
#include "AI2C_mdlheader.h"

#ifdef GAMECUBE_USE_AI2C_DLL

#define AI2C_FCTDEFTRIGGER(a, b, c) 
#define AI2C_FCTDEF(a, b)	extern int (*AI2C_pfi_##b) (void);
#include "AI2C_fctdefs.h"
#undef AI2C_FCTDEF

#undef AI2C_FCTDEFTRIGGER

#define AI2C_FCTDEFTRIGGER(a, b, c) 
#define AI2C_FCTDEF(a, b)	extern int	  b(void);
#include "AI2C_fctdefs.h"
#undef AI2C_FCTDEF


#undef AI2C_FCTDEFTRIGGER

/*
 ***********************************************************************************************************************
    AI functions includes
 ***********************************************************************************************************************
*/

/*
 =======================================================================================================================
 =======================================================================================================================
*/
extern "C"
{

void AI2C_InitFix(void)
{
}

}
#endif /* GAMECUBE_USE_AI2C_DLL */
/*
 ***********************************************************************************************************************
    EOF
 ***********************************************************************************************************************
*/
