add_library(Jaded-Engine OBJECT
        Sources/ENGcall.c
        Sources/ENGcall.h
        Sources/ENGinit.cpp
        Sources/ENGinit.h
        Sources/ENGloop.cpp
        Sources/ENGloop.h
        Sources/ENGmsg.c
        Sources/ENGmsg.h
        Sources/ENGstring.h
        Sources/ENGstruct.h
        Sources/ENGvars.c
        Sources/ENGvars.h
        Sources/Precomp.c
        Sources/Precomp.h
        Sources/ACTions/ACTcompute.c
        Sources/ACTions/ACTcompute.h
        Sources/ACTions/ACTinit.h
        Sources/ACTions/ACTload.c
        Sources/ACTions/ACTload.h
        Sources/ACTions/ACTsave.c
        Sources/ACTions/ACTsave.h
        Sources/ACTions/ACTstruct.h
        Sources/ANImation/ANI.c
        Sources/ANImation/ANI.h
        Sources/ANImation/ANIaccess.h
        Sources/ANImation/ANIinit.c
        Sources/ANImation/ANIinit.h
        Sources/ANImation/ANIload.c
        Sources/ANImation/ANIload.h
        Sources/ANImation/ANImain.c
        Sources/ANImation/ANImain.h
        Sources/ANImation/ANIplay.c
        Sources/ANImation/ANIplay.h
        Sources/ANImation/ANIrender.c
        Sources/ANImation/ANIrender.h
        Sources/ANImation/ANIsave.c
        Sources/ANImation/ANIsave.h
        Sources/ANImation/ANIstruct.h
        Sources/ANImation/NIMtoTracks.c
        Sources/ANImation/NIMtoTracks.h
        Sources/COLlision/COL.c
        Sources/COLlision/COL.h
        Sources/COLlision/COLaccess.h
        Sources/COLlision/COLactor.c
        Sources/COLlision/COLactor.h
        Sources/COLlision/COLcob.c
        Sources/COLlision/COLcob.h
        Sources/COLlision/COLconst.h
        Sources/COLlision/COLedit.c
        Sources/COLlision/COLedit.h
        Sources/COLlision/COLinit.c
        Sources/COLlision/COLinit.h
        Sources/COLlision/COLinst.c
        Sources/COLlision/COLinst.h
        Sources/COLlision/COLload.c
        Sources/COLlision/COLload.h
        Sources/COLlision/COLmain.cpp
        Sources/COLlision/COLmain.h
        Sources/COLlision/COLray.c
        Sources/COLlision/COLray.h
        Sources/COLlision/COLreport.c
        Sources/COLlision/COLreport.h
        Sources/COLlision/COLsave.c
        Sources/COLlision/COLsave.h
        Sources/COLlision/COLset.c
        Sources/COLlision/COLset.h
        Sources/COLlision/COLstruct.h
        Sources/COLlision/COLvars.h
        Sources/COLlision/COLzdx.c
        Sources/COLlision/COLzdx.h
        #Sources/DEModisk/DEModisk.c
        #Sources/DEModisk/DEModisk.h
        Sources/DYNamics/DYN.c
        Sources/DYNamics/DYN.h
        Sources/DYNamics/DYNaccess.c
        Sources/DYNamics/DYNaccess.h
        Sources/DYNamics/DYNBasic.c
        Sources/DYNamics/DYNBasic.h
        Sources/DYNamics/DYNcol.c
        Sources/DYNamics/DYNcol.h
        Sources/DYNamics/DYNconst.h
        Sources/DYNamics/DYNConstraint.c
        Sources/DYNamics/DYNConstraint.h
        Sources/DYNamics/DYNinit.c
        Sources/DYNamics/DYNinit.h
        Sources/DYNamics/DYNmain.c
        Sources/DYNamics/DYNmain.h
        Sources/DYNamics/DYNSolid.c
        Sources/DYNamics/DYNsolid.h
        Sources/DYNamics/DYNstruct.h
        Sources/DYNamics/DYNvars.c
        Sources/DYNamics/DYNvars.h
        Sources/EOT/EOT.c
        Sources/EOT/EOT.h
        Sources/EOT/EOTconst.h
        Sources/EOT/EOTinit.c
        Sources/EOT/EOTinit.h
        Sources/EOT/EOTmain.c
        Sources/EOT/EOTmain.h
        Sources/EOT/EOTstruct.h
        Sources/GEOMETRICEVENT/Partitioner/CPlane.h
        Sources/GRId/GRI_compute.c
        Sources/GRId/GRI_compute.h
        Sources/GRId/GRI_display.c
        Sources/GRId/GRI_display.h
        Sources/GRId/GRI_load.c
        Sources/GRId/GRI_load.h
        Sources/GRId/GRI_save.c
        Sources/GRId/GRI_save.h
        Sources/GRId/GRI_struct.h
        Sources/GRId/GRI_vars.c
        Sources/GRId/GRI_vars.h
        Sources/GRP/GRPload.c
        Sources/GRP/GRPload.h
        Sources/GRP/GRPmain.c
        Sources/GRP/GRPmain.h
        Sources/GRP/GRPorient.c
        Sources/GRP/GRPorient.h
        Sources/GRP/GRPsave.c
        Sources/GRP/GRPsave.h
        Sources/INTersection/INT.c
        Sources/INTersection/INT.h
        Sources/INTersection/INTaccess.cpp
        Sources/INTersection/INTaccess.h
        Sources/INTersection/INTConst.h
        Sources/INTersection/INTinit.cpp
        Sources/INTersection/INTinit.h
        Sources/INTersection/INTmain.cpp
        Sources/INTersection/INTmain.h
        Sources/INTersection/INTSnP.cpp
        Sources/INTersection/INTSnP.h
        Sources/INTersection/INTstruct.h
        Sources/MoDiFier/MDFmodifier_BrumeDynamique.c
        Sources/MoDiFier/MDFmodifier_BrumeDynamique.h
        Sources/MoDiFier/MDFmodifier_Disturber.c
        Sources/MoDiFier/MDFmodifier_Disturber.h
        Sources/MoDiFier/MDFmodifier_FCLONE.c
        Sources/MoDiFier/MDFmodifier_FCLONE.h
        Sources/MoDiFier/MDFmodifier_FUR.c
        Sources/MoDiFier/MDFmodifier_FUR.h
        Sources/MoDiFier/MDFmodifier_GAO.c
        Sources/MoDiFier/MDFmodifier_GAO.h
        Sources/MoDiFier/MDFmodifier_GEN.c
        Sources/MoDiFier/MDFmodifier_GEN.h
        Sources/MoDiFier/MDFmodifier_GEO.c
        Sources/MoDiFier/MDFmodifier_GEO.h
        Sources/MoDiFier/MDFmodifier_GPG.c
        Sources/MoDiFier/MDFmodifier_GPG.h
        Sources/MoDiFier/MDFmodifier_GRID.c
        Sources/MoDiFier/MDFmodifier_GRID.h
        Sources/MoDiFier/MDFmodifier_LAZY.c
        Sources/MoDiFier/MDFmodifier_LAZY.h
        Sources/MoDiFier/MDFmodifier_MatrixBore.c
        Sources/MoDiFier/MDFmodifier_MatrixBore.h
        Sources/MoDiFier/MDFmodifier_MPAG.c
        Sources/MoDiFier/MDFmodifier_MPAG.h
        Sources/MoDiFier/MDFmodifier_ODE.c
        Sources/MoDiFier/MDFmodifier_ODE.h
        Sources/MoDiFier/MDFmodifier_PROTEX.c
        Sources/MoDiFier/MDFmodifier_PROTEX.h
        Sources/MoDiFier/MDFmodifier_ROTR.c
        Sources/MoDiFier/MDFmodifier_ROTR.h
        Sources/MoDiFier/MDFmodifier_SDW.c
        Sources/MoDiFier/MDFmodifier_SDW.h
        Sources/MoDiFier/MDFmodifier_SFX.c
        Sources/MoDiFier/MDFmodifier_SFX.h
        Sources/MoDiFier/MDFmodifier_SNAKE.c
        Sources/MoDiFier/MDFmodifier_SNAKE.h
        Sources/MoDiFier/MDFmodifier_SNDVOL.c
        Sources/MoDiFier/MDFmodifier_SNDVOL.h
        #Sources/MoDiFier/MDFmodifier_SoftBody.c
        #Sources/MoDiFier/MDFmodifier_SoftBody.h
        Sources/MoDiFier/MDFmodifier_SOUNDFX.c
        Sources/MoDiFier/MDFmodifier_SOUNDFX.h
        Sources/MoDiFier/MDFmodifier_SOUNDLOADING.c
        Sources/MoDiFier/MDFmodifier_SOUNDLOADING.h
        Sources/MoDiFier/MDFmodifier_SPG.c
        Sources/MoDiFier/MDFmodifier_SPG.h
        Sources/MoDiFier/MDFmodifier_SPG2.c
        Sources/MoDiFier/MDFmodifier_SPG2.h
        #Sources/MoDiFier/MDFmodifier_SPG2_Holder.c
        #Sources/MoDiFier/MDFmodifier_SPG2_Holder.h
        #Sources/MoDiFier/MDFmodifier_trb.c
        #Sources/MoDiFier/MDFmodifier_trb.h
        Sources/MoDiFier/MDFmodifier_UVTexWave.c
        Sources/MoDiFier/MDFmodifier_UVTexWave.h
        Sources/MoDiFier/MDFmodifier_Vine.c
        Sources/MoDiFier/MDFmodifier_Vine.h
        Sources/MoDiFier/MDFmodifier_WATER3D.c
        Sources/MoDiFier/MDFmodifier_WATER3D.h
        Sources/MoDiFier/MDFmodifier_Weather.c
        Sources/MoDiFier/MDFmodifier_Weather.h
        #Sources/MoDiFier/MDFmodifier_Wind.c
        #Sources/MoDiFier/MDFmodifier_Wind.h
        Sources/MoDiFier/MDFmodifier_XMEC.c
        Sources/MoDiFier/MDFmodifier_XMEC.h
        Sources/MoDiFier/MDFmodifier_XMEN.cpp
        Sources/MoDiFier/MDFmodifier_XMEN.h
        Sources/MoDiFier/MDFstruct.c
        Sources/MoDiFier/MDFstruct.h
        Sources/OBJects/OBJ.c
        Sources/OBJects/OBJ.h
        Sources/OBJects/OBJaccess.h
        Sources/OBJects/OBJBoundingvolume.c
        Sources/OBJects/OBJBoundingVolume.h
        Sources/OBJects/OBJconst.h
        Sources/OBJects/OBJculling.c
        Sources/OBJects/OBJculling.h
        Sources/OBJects/OBJdef.h
        Sources/OBJects/OBJgizmo.c
        Sources/OBJects/OBJgizmo.h
        Sources/OBJects/OBJgrp.c
        Sources/OBJects/OBJgrp.h
        Sources/OBJects/OBJinit.c
        Sources/OBJects/OBJinit.h
        Sources/OBJects/OBJload.c
        Sources/OBJects/OBJload.h
        Sources/OBJects/OBJmain.c
        Sources/OBJects/OBJmain.h
        Sources/OBJects/OBJODE.c
        Sources/OBJects/OBJODE.h
        Sources/OBJects/OBJorient.c
        Sources/OBJects/OBJorient.h
        Sources/OBJects/OBJsave.c
        Sources/OBJects/OBJsave.h
        Sources/OBJects/OBJslowaccess.c
        Sources/OBJects/OBJslowaccess.h
        Sources/OBJects/OBJstruct.h
        Sources/RECalage/REC.c
        Sources/RECalage/REC.h
        Sources/RECalage/RECconst.h
        Sources/RECalage/RECdyn.c
        Sources/RECalage/RECdyn.h
        Sources/TEXT/TEXT.c
        Sources/TEXT/TEXT.h
        Sources/TEXT/TEXTload.c
        Sources/TEXT/TEXTload.h
        Sources/TEXT/TEXTstruct.h
        Sources/WAYs/WAY.c
        Sources/WAYs/WAY.h
        Sources/WAYs/WAYerrid.h
        Sources/WAYs/WAYinit.c
        Sources/WAYs/WAYinit.h
        Sources/WAYs/WAYload.c
        Sources/WAYs/WAYload.h
        Sources/WAYs/WAYsave.c
        Sources/WAYs/WAYsave.h
        Sources/WAYs/WAYstruct.h
        Sources/Wind/CurrentWind.cpp
        Sources/Wind/CurrentWind.h
        Sources/Wind/Noise.cpp
        Sources/Wind/noise.h
        Sources/Wind/WindManager.cpp
        Sources/Wind/WindManager.h
        Sources/Wind/WindSource.cpp
        Sources/Wind/WindSource.h
        Sources/WORld/WOR.c
        Sources/WORld/WOR.h
        Sources/WORld/WORaccess.h
        Sources/WORld/WORcheck.c
        Sources/WORld/WORcheck.h
        Sources/WORld/WORconst.h
        Sources/WORld/WORexport.cpp
        Sources/WORld/WORexport.h
        Sources/WORld/WORexporttomad.c
        Sources/WORld/WORexporttomad.h
        Sources/WORld/WORimportfrommad.c
        Sources/WORld/WORimportfrommad.h
        Sources/WORld/WORinit.c
        Sources/WORld/WORinit.h
        Sources/WORld/WORload.c
        Sources/WORld/WORload.h
        Sources/WORld/WORmain.c
        Sources/WORld/WORmain.h
        Sources/WORld/WORrender.c
        Sources/WORld/WORrender.h
        Sources/WORld/WORsave.c
        Sources/WORld/WORsave.h
        Sources/WORld/WORsecto.c
        Sources/WORld/WORsecto.h
        Sources/WORld/WORstruct.h
        Sources/WORld/WORuniverse.c
        Sources/WORld/WORuniverse.h
        Sources/WORld/WORupdate.c
        Sources/WORld/WORupdate.h
        Sources/WORld/WORvars.c
        Sources/WORld/WORvars.h
        Sources/WORld/WOR_Gos.c
)

target_include_directories(Jaded-Engine
        PUBLIC
        Sources

        PRIVATE
        #TODO: clean this up
        ../../Extern/ode/include
        ../../Extern/sdl3/include
        ../../Main/WinEditors/Sources
        ../../Dlls
)

target_link_libraries(Jaded-Engine Jaded-SDK)
set_target_properties(Jaded-Engine PROPERTIES FOLDER "Libraries")
