add_library(Jaded-Sound OBJECT
    Sources/MTX.c
    Sources/MTX.h
    Sources/Precomp.c
    Sources/Precomp.h
    Sources/SND.c
    Sources/SND.h
    Sources/SNDambience.c
    Sources/SNDambience.h
    Sources/SNDbank.c
    Sources/SNDbank.h
    Sources/SNDconst.h
    Sources/SNDconv.c
    Sources/SNDconv.h
    Sources/SNDconv_pcretailadpcm.c
    Sources/SNDconv_pcretailadpcm.h
    Sources/SNDconv_xboxadpcm.c
    Sources/SNDconv_xboxadpcm.h
    Sources/SNDdebug.c
    Sources/SNDdebug.h
    Sources/SNDdialog.c
    Sources/SNDdialog.h
    Sources/SNDdirect.c
    Sources/SNDdirect.h
    Sources/SNDerrid.h
    Sources/SNDfx.c
    Sources/SNDfx.h
    Sources/SNDinsert.c
    Sources/SNDinsert.h
    Sources/SNDinterface.c
    Sources/SNDinterface.h
    Sources/SNDload.c
    Sources/SNDload.h
    Sources/SNDloadingsound.c
    Sources/SNDloadingsound.h
    Sources/SNDmacros.h
    Sources/SNDmodifier.c
    Sources/SNDmodifier.h
    Sources/SNDmsadpcm.c
    Sources/SNDmsadpcm.h
    Sources/SNDmusic.c
    Sources/SNDmusic.h
    Sources/SNDrasters.c
    Sources/SNDrasters.h
    Sources/SNDspecific.h
    Sources/SNDstream.c
    Sources/SNDstream.h
    Sources/SNDstruct.h
    Sources/SNDtrack.c
    Sources/SNDtrack.h
    Sources/SNDvolume.c
    Sources/SNDvolume.h
    Sources/SNDwave.c
    Sources/SNDwave.h
    Sources/edi/ediSND.c
    Sources/edi/ediSND.h
    Sources/edi/ediSNDdebug.c
    Sources/edi/ediSNDdebug.h
    Sources/edi/ediSNDfx.c
    Sources/edi/ediSND_Stream.c
    Sources/edi/ediSND_Stream.h
    #Sources/gc/gcSND.c
    #Sources/gc/gcSND.h
    #Sources/gc/gcSNDfx.c
    #Sources/gc/gcSNDfx.h
    #Sources/gc/gcSND_ARAM.c
    #Sources/gc/gcSND_ARAM.h
    #Sources/gc/gcSND_AudioFrame.c
    #Sources/gc/gcSND_AudioFrame.h
    #Sources/gc/gcSND_Debug.c
    #Sources/gc/gcSND_Debug.h
    #Sources/gc/gcSND_Prefetch.c
    #Sources/gc/gcSND_Prefetch.h
    #Sources/gc/gcSND_Profile.c
    #Sources/gc/gcSND_Profile.h
    #Sources/gc/gcSND_Soft.c
    #Sources/gc/gcSND_Soft.h
    #Sources/gc/gcSND_Stream.c
    #Sources/gc/gcSND_Stream.h
    #Sources/pcretail/pcretailSND.c
    #Sources/pcretail/pcretailSND.h
    #Sources/pcretail/pcretailSNDfx.c
    #Sources/pcretail/pcretailSNDfx.h
    #Sources/ps2/ps2SND.c
    #Sources/ps2/ps2SND.h
    #Sources/ps2/ps2SNDdebug.c
    #Sources/ps2/ps2SNDfx.c
    #Sources/ps2/ps2SNDstream.c
    #Sources/ps2/SPU.c
    #Sources/ps2/SPU.h
    Sources/win32/win32SND.c
    Sources/win32/win32SND.h
    Sources/win32/win32SNDdebug.c
    Sources/win32/win32SNDdebug.h
    Sources/win32/win32SNDfx.c
    Sources/win32/win32SNDfx.h
    Sources/win32/win32SND_Stream.c
    Sources/win32/win32SND_Stream.h
    #Sources/xbox/dsstdfx.h
    #Sources/xbox/jadedsp.bin
    #Sources/xbox/jadedsp.dspfx
    #Sources/xbox/jadedsp.h
    #Sources/xbox/jadedsp.ini
    #Sources/xbox/jadedsp_0StereoEchoA_state.ini
    #Sources/xbox/jadedsp_1StereoEchoB_state.ini
    #Sources/xbox/jadedsp_32x1Mixer_state.ini
    #Sources/xbox/jadedsp_5XTalk_state.ini
    #Sources/xbox/reverb_Alley_24k_state.ini
    #Sources/xbox/reverb_Room_24k_state.ini
    #Sources/xbox/xbSND.c
    #Sources/xbox/xbSND.h
    #Sources/xbox/xbSNDfx.c
    #Sources/xbox/xbSNDfx.h
    #Sources/xbox/xbSND_debug.c
    #Sources/xbox/xbSND_debug.h
    #Sources/xbox/xbSND_RAM.c
    #Sources/xbox/xbSND_RAM.h
    #Sources/xbox/xbSND_Stream.c
    #Sources/xbox/xbSND_Stream.h
    #Sources/xbox/xbSND_Thread.c
    #Sources/xbox/xbSND_Thread.h
    #Sources/xenon/xeSND_ADPCM.cpp
    #Sources/xenon/xeSND_ADPCM.h
    #Sources/xenon/xeSND_AudioConsole.cpp
    #Sources/xenon/xeSND_AudioConsole.h
    #Sources/xenon/xeSND_BigFile.cpp
    #Sources/xenon/xeSND_BigFile.h
    #Sources/xenon/xeSND_Database.cpp
    #Sources/xenon/xeSND_Database.h
    #Sources/xenon/xeSND_Effects.cpp
    #Sources/xenon/xeSND_Effects.h
    #Sources/xenon/xeSND_Engine.cpp
    #Sources/xenon/xeSND_Engine.h
    #Sources/xenon/xeSND_Helpers.cpp
    #Sources/xenon/xeSND_Helpers.h
    #Sources/xenon/xeSND_Interface.cpp
    #Sources/xenon/xeSND_Interface.h
    #Sources/xenon/xeSND_Voice.cpp
    #Sources/xenon/xeSND_Voice.h
    #Sources/xenon/xeSND_WaveParser.cpp
    #Sources/xenon/xeSND_WaveParser.h
)

target_include_directories(Jaded-Sound
        PUBLIC
        Sources

        PRIVATE
        #TODO: clean this up
        ../../Extern/ode/include
        #../../Extern/sdl3/include
        ../../Main/WinEditors/Sources
        ../../Dlls
)

target_link_libraries(Jaded-Sound Jaded-SDK Jaded-Engine)
set_target_properties(Jaded-Sound PROPERTIES FOLDER "Libraries")
