//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoCompiler.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AUTOCOMPILER_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ChangeString         129
#define IDD_DIALOG_SETTINGS             132
#define IDD_DIALOG_MapTesting           135
#define IDD_DIALOG_ChangePatchNumbers   136
#define IDC_BUTTON_Suspend              1012
#define IDC_BUTTON_SuspendServer        1013
#define IDC_STATIC_DesdacVersion        1014
#define IDC_BUTTON_ServerPort           1015
#define IDC_EditChangeString            1017
#define IDC_BUTTON_ServerBranch         1018
#define IDC_BUTTON_UserName             1019
#define IDC_BUTTON_PasswordFile         1020
#define IDC_BUTTON_ExeName              1021
#define IDC_BUTTON_BigFileName          1022
#define IDC_STATIC_ResultGroup          1023
#define IDC_STATIC_LastCL               1024
#define IDC_STATIC_LastCLValue          1025
#define IDC_STATIC_Owner                1026
#define IDC_STATIC_OwnerValue           1027
#define IDC_STATIC_AiResult             1028
#define IDC_STATIC_AiResultValue        1029
#define IDC_STATIC_DbResult             1030
#define IDC_STATIC_DbResultValue        1031
#define IDC_STATIC_GlobalResult         1032
#define IDC_STATIC_GlobalResultValue    1033
#define IDC_STATIC_CLSTACK              1034
#define IDC_STATIC_NbClInStack          1035
#define IDC_STATIC_NextCl               1036
#define IDC_STATIC_NbClInStackValue     1037
#define IDC_STATIC_NextClValue          1038
#define IDC_STATIC_Working              1039
#define IDC_BUTTON_CHANGESETTINGS       1040
#define IDC_BUTTON_PERFORCESERVER       1041
#define IDC_STATIC_Patch                1042
#define IDC_BUTTON_PERFORCEUSER         1043
#define IDC_STATIC_PatchValue           1044
#define IDC_BUTTON_PERFORCEBRANCH       1045
#define IDC_STATIC_LastUpdated          1046
#define IDC_STATIC_LastUpdatedValue     1047
#define IDC_STATIC_NbMapToTest          1048
#define IDC_BUTTON_YETIEXENAME          1049
#define IDC_STATIC_TestFirstCl          1050
#define IDC_STATIC_NbMapToTestValue     1051
#define IDC_BUTTON_BIGFILE              1052
#define IDC_STATIC_TestLastCl           1053
#define IDC_STATIC_CLIENTSERVER         1054
#define IDC_CHECK_SERVER                1055
#define IDC_LIST_CLIENTS                1056
#define IDC_BUTTON_ADDCLIENT            1057
#define IDC_STATIC_NBCLIENTS            1058
#define IDC_STATIC_NBCLIENTSVALUE       1059
#define IDC_STATIC_NBRUNNINGCLIENTS     1060
#define IDC_BUTTON_REMOVECLIENT         1061
#define IDC_STATIC_NBRUNNINGCLIENTSVALUE 1062
#define IDC_LIST_Mails                  1063
#define IDC_BUTTON_CLIENTPASSWORD       1064
#define IDC_STATIC_NBIDDLECLIENTS       1065
#define IDC_BUTTON_PCSERVER             1066
#define IDC_STATIC_NBIDDLECLIENTSVALUE  1067
#define IDC_STATIC_PERFORCECONFIG       1068
#define IDC_STATIC_NBDOWNCLIENTS        1069
#define IDC_STATIC_YETICONFIGURATION    1070
#define IDC_STATIC_NBDOWNCLIENTSVALUE   1071
#define IDC_STATIC_NBNOTLAUNCHEDCLIENTS 1072
#define IDC_STATIC_NBNOTLAUNCHEDCLIENTSVALUE 1073
#define IDC_STATIC_NBSUSPENDEDCLIENTS   1074
#define IDC_STATIC_CLIENTSINFOS         1075
#define IDC_STATIC_DESDACCONFIG         1076
#define IDC_STATIC_NBUPDATINGCLIENTS    1076
#define IDC_STATIC_NBSUSPENDEDCLIENTSVALUE 1077
#define IDC_LIST_CLIENTINFO             1078
#define IDC_BUTTON_CLIENTREFRESH        1079
#define IDC_LIST_CLIENTINFO2            1080
#define IDC_SLIDER_SYNCDEPTH            1081
#define IDC_BUTTON_DLGCLIENTREFRESH     1082
#define IDC_STATIC_SYNCDEPTH            1083
#define IDC_STATIC_SNCDEPTH0            1084
#define IDC_STATIC_SNCDEPTH5            1085
#define IDC_STATIC_YETIINFOS            1086
#define IDC_BUTTON_ForceUpdateVersion   1087
#define IDC_STATIC_MapTesting           1088
#define IDC_CHECK_MapTestingEnable      1089
#define IDC_BUTTON_MapTestingConfiguration 1090
#define IDC_LIST_MapTesting             1091
#define IDC_BUTTON_AddMapToTest         1092
#define IDC_BUTTON_RemoveMapToTest      1093
#define IDC_BUTTON_UpdateNumbers        1094
#define IDC_SPIN_VersionNumber          1095
#define IDC_SPIN_PatchNumber            1096
#define IDC_STATIC_VersionNumber        1097
#define IDC_STATIC_PatchNumber          1098
#define IDC_STATIC_VersionNumberValue   1099
#define IDC_STATIC_PatchNumberValue2    1100
#define IDC_BUTTON_AddMail              1101
#define IDC_BUTTON_RemoveMail           1102
#define IDC_CHECK_SendMails             1103
#define IDC_CHECK_SendMailsUser         1104
#define IDC_BUTTON_FlushCLStack         1105
#define IDC_STATIC_LastSubmittedCl      1106
#define IDC_STATIC_LastSubmittedClValue 1107
#define IDC_STATIC_MapTestResult        1108
#define IDC_STATIC_MapTestResultValue   1109
#define IDC_STATIC_MapTestingXenon      1110
#define IDC_CHECK_MapTestingXenonEnable 1111
#define IDC_STATIC_NBUPDATINGCLIENTSVALUE 1112
#define IDC_BUTTON_RELOADINI            1113
#define IDC_CHECK_TestLastCLonly        1114
#define IDC_BUTTON1                     1116
#define IDC_STATIC_AITOC                1117
#define IDC_CHECK1                      1118
#define IDC_CHECK_AITOC                 1119
#define IDC_BUTTON_JADESOL              1120
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
