add_library(Jaded-SDK OBJECT
        Sources/Precomp.h
        Sources/projectconfig.h
        Sources/BASe/BAS.c
        Sources/BASe/BAS.h
        Sources/BASe/BASarray.c
        Sources/BASe/BASarray.h
        Sources/BASe/BAScrc.cpp
        Sources/BASe/BAScrc.h
        Sources/BASe/BASlog.c
        Sources/BASe/BASlog.h
        Sources/BASe/BASsys.h
        Sources/BASe/BAStypes.h
        Sources/BASe/BASversion.h
        Sources/BASe/BENch/BENch.h
        Sources/BASe/BENch/BENch_RasterDef.h
        Sources/BASe/CLIbrary/CLIerrid.h
        Sources/BASe/CLIbrary/CLIfile.h
        Sources/BASe/CLIbrary/CLImem.h
        Sources/BASe/CLIbrary/CLIstr.c
        Sources/BASe/CLIbrary/CLIstr.h
        Sources/BASe/CLIbrary/CLIwin.h
        Sources/BASe/CLIbrary/CLIxxx.c
        Sources/BASe/CLIbrary/CLIxxx.h
        Sources/BASe/ERRors/ERR.c
        Sources/BASe/ERRors/ERR.h
        Sources/BASe/ERRors/ERRasser.h
        Sources/BASe/ERRors/ERRdefs.cpp
        Sources/BASe/ERRors/ERRdefs.h
        Sources/BASe/ERRors/ERRstr.h
        Sources/BASe/MEMory/MEM.h
        Sources/BASe/MEMory/MEMdyn.c
        Sources/BASe/MEMory/MEMdynOpt.c
        Sources/BASe/MEMory/MEMLog.c
        Sources/BASe/MEMory/MEMLog.h
        Sources/BASe/MEMory/MEMLogOpt.c
        Sources/BASe/MEMory/MEMpro.c
        Sources/BASe/MEMory/MEMpro.h
        Sources/BASe/MEMory/MEMproOpt.c
        #Sources/BASe/XBox/XBCompositeFile.c
        #Sources/BASe/XBox/XBCompositeFile.h
        Sources/BIGfiles/BIG.c
        Sources/BIGfiles/BIG.h
        Sources/BIGfiles/BIGcheck.c
        Sources/BIGfiles/BIGcheck.h
        Sources/BIGfiles/BIGchecksum.c
        Sources/BIGfiles/BIGchecksum.h
        Sources/BIGfiles/BIGcomp.c
        Sources/BIGfiles/BIGcomp.h
        Sources/BIGfiles/BIGdefs.c
        Sources/BIGfiles/BIGdefs.h
        Sources/BIGfiles/BIGerrid.h
        Sources/BIGfiles/BIGexport.c
        Sources/BIGfiles/BIGexport.h
        Sources/BIGfiles/BIGfat.c
        Sources/BIGfiles/BIGfat.h
        Sources/BIGfiles/BIGgroup.c
        Sources/BIGfiles/BIGgroup.h
        Sources/BIGfiles/BIGio.c
        Sources/BIGfiles/BIGio.h
        Sources/BIGfiles/BIGkey.c
        Sources/BIGfiles/BIGkey.h
        Sources/BIGfiles/BIGmdfy_dir.c
        Sources/BIGfiles/BIGmdfy_dir.h
        Sources/BIGfiles/BIGmdfy_file.c
        Sources/BIGfiles/BIGmdfy_file.h
        Sources/BIGfiles/BIGmerge.c
        Sources/BIGfiles/BIGmerge.h
        Sources/BIGfiles/BIGopen.c
        Sources/BIGfiles/BIGopen.h
        Sources/BIGfiles/BIGread.c
        Sources/BIGfiles/BIGread.h
        Sources/BIGfiles/BIGspecial.c
        Sources/BIGfiles/BIGspecial.h
        Sources/BIGfiles/lzoconf.h
        Sources/BIGfiles/minilzo.c
        Sources/BIGfiles/minilzo.h
        Sources/BIGfiles/IMPort/IMPbase.c
        Sources/BIGfiles/IMPort/IMPbase.h
        Sources/BIGfiles/LOAding/LOA.c
        Sources/BIGfiles/LOAding/LOA.h
        Sources/BIGfiles/LOAding/LOAdefs.c
        Sources/BIGfiles/LOAding/LOAdefs.h
        Sources/BIGfiles/LOAding/LOAerrid.h
        Sources/BIGfiles/LOAding/LOAread.c
        Sources/BIGfiles/LOAding/LOAread.h
        Sources/BIGfiles/SAVing/SAVdefs.c
        Sources/BIGfiles/SAVing/SAVdefs.h
        Sources/BIGfiles/STReams/STReamaccess.cpp
        Sources/BIGfiles/STReams/STReamaccess.h
        Sources/BIGfiles/STReams/STReamBigFile.cpp
        Sources/BIGfiles/STReams/STReamBigFile.h
        Sources/BIGfiles/VERsion/VERsion_Check.cpp
        Sources/BIGfiles/VERsion/VERsion_Check.h
        Sources/BIGfiles/VERsion/VERsion_Number.h
        Sources/BIGfiles/VERsion/VERsion_Update.cpp
        Sources/BIGfiles/VERsion/VERsion_Update.h
        Sources/BIGfiles/VERsion/VERsion_Update10.cpp
        Sources/BIGfiles/VERsion/VERsion_Update11.cpp
        Sources/BIGfiles/VERsion/VERsion_Update12.cpp
        Sources/BIGfiles/VERsion/VERsion_Update13.cpp
        Sources/BIGfiles/VERsion/VERsion_Update14.cpp
        Sources/BIGfiles/VERsion/VERsion_Update15.cpp
        Sources/BIGfiles/VERsion/VERsion_Update16.cpp
        Sources/BIGfiles/VERsion/VERsion_Update17.cpp
        Sources/BIGfiles/VERsion/VERsion_Update18.cpp
        Sources/BIGfiles/VERsion/VERsion_Update19.cpp
        Sources/BIGfiles/VERsion/VERsion_Update2.cpp
        Sources/BIGfiles/VERsion/VERsion_Update20.cpp
        Sources/BIGfiles/VERsion/VERsion_Update21.cpp
        Sources/BIGfiles/VERsion/VERsion_Update22.cpp
        Sources/BIGfiles/VERsion/VERsion_Update23.cpp
        Sources/BIGfiles/VERsion/VERsion_Update24.cpp
        Sources/BIGfiles/VERsion/VERsion_Update25.cpp
        Sources/BIGfiles/VERsion/VERsion_Update26.cpp
        Sources/BIGfiles/VERsion/VERsion_Update27.cpp
        Sources/BIGfiles/VERsion/VERsion_Update28.cpp
        Sources/BIGfiles/VERsion/VERsion_Update29.cpp
        Sources/BIGfiles/VERsion/VERsion_Update3.cpp
        Sources/BIGfiles/VERsion/VERsion_Update30.cpp
        Sources/BIGfiles/VERsion/VERsion_Update31.cpp
        Sources/BIGfiles/VERsion/VERsion_Update32.cpp
        Sources/BIGfiles/VERsion/VERsion_Update33.cpp
        Sources/BIGfiles/VERsion/VERsion_Update34.cpp
        Sources/BIGfiles/VERsion/VERsion_Update35.cpp
        Sources/BIGfiles/VERsion/VERsion_Update36.cpp
        Sources/BIGfiles/VERsion/VERsion_Update4.cpp
        Sources/BIGfiles/VERsion/VERsion_Update5.cpp
        Sources/BIGfiles/VERsion/VERsion_Update6.cpp
        Sources/BIGfiles/VERsion/VERsion_Update7.cpp
        Sources/BIGfiles/VERsion/VERsion_Update8.cpp
        Sources/BIGfiles/VERsion/VERsion_Update9.cpp
        Sources/INOut/INO.c
        Sources/INOut/INO.h
        Sources/INOut/INOfile.c
        Sources/INOut/INOfile.h
        Sources/INOut/INOjoystick.c
        Sources/INOut/INOjoystick.h
        Sources/INOut/INOkeyboard.c
        Sources/INOut/INOkeyboard.h
        Sources/INOut/INOlang.c
        Sources/INOut/INOsaving.c
        Sources/INOut/INOsaving.h
        Sources/INOut/INOstruct.h
        Sources/INOut/win32/win32INOsaving.c
        Sources/INOut/win32/win32INOsaving.h
        Sources/LINks/LINK.cpp
        Sources/LINks/LINK.h
        Sources/LINks/LINKmsg.cpp
        Sources/LINks/LINKmsg.h
        Sources/LINks/LINKstruct.cpp
        Sources/LINks/LINKstruct.h
        Sources/LINks/LINKstruct_reg.cpp
        Sources/LINks/LINKstruct_reg.h
        Sources/LINks/LINKtoed.cpp
        Sources/LINks/LINKtoed.h
        Sources/MATHs/MATH.c
        Sources/MATHs/MATH.h
        Sources/MATHs/MATHasm.h
        Sources/MATHs/MATHconst.h
        Sources/MATHs/MATHdebug.c
        Sources/MATHs/MATHdebug.h
        Sources/MATHs/MATHextern.h
        Sources/MATHs/MATHfloat.h
        Sources/MATHs/MATHinit.c
        Sources/MATHs/MATHinit.h
        Sources/MATHs/MATHlong.h
        Sources/MATHs/MATHmatrix.h
        Sources/MATHs/MATHmatrixAdvanced.c
        Sources/MATHs/MATHmatrixAdvanced.h
        Sources/MATHs/MATHmatrixBase.c
        Sources/MATHs/MATHmatrixBase.h
        Sources/MATHs/MATHmatrixRot.c
        Sources/MATHs/MATHmatrixRot.h
        Sources/MATHs/MATHmatrixScale.c
        Sources/MATHs/MATHmatrixScale.h
        Sources/MATHs/MATHmatrixTrans.h
        Sources/MATHs/MATHmatrixTransform.c
        Sources/MATHs/MATHmatrixTransform.h
        Sources/MATHs/MATHquat.h
        Sources/MATHs/MATHstruct.h
        Sources/MATHs/MATHvars.c
        Sources/MATHs/MATHvars.h
        Sources/MATHs/MATHvector.h
        Sources/MATHs/MATHvector_ALIGNED.h
        Sources/MATHs/MATH_MEM.c
        Sources/MATHs/MATH_MEM.h
        Sources/MATHs/ix86/ix86MATHfloat.h
        Sources/Random/PerlinNoise.c
        Sources/Random/PerlinNoise.h
        Sources/Random/random.h
        Sources/TABles/TABles.c
        Sources/TABles/TABles.h
        Sources/TABles/TABvars.c
        Sources/TABles/TABvars.h
        Sources/TIMer/TIM.c
        Sources/TIMer/TIM.h
        Sources/TIMer/TIMdefs.c
        Sources/TIMer/TIMdefs.h
        Sources/TIMer/PROfiler/PRO.c
        Sources/TIMer/PROfiler/PRO.h
        Sources/TIMer/PROfiler/PROdefs.c
        Sources/TIMer/PROfiler/PROdefs.h
        Sources/TIMer/PROfiler/PROdisplay.c
        Sources/TIMer/PROfiler/PROdisplay.h
        Sources/TIMer/PROfiler/PROPS2.c
        Sources/TIMer/PROfiler/PROPS2.h
        Sources/TIMer/PROfiler/PROPS2_def.h
)

target_include_directories(Jaded-SDK
        PUBLIC
        Sources

        PRIVATE
        #TODO: clean this up
        ../../Extern/ode/include
        ../../Extern/sdl3/include
        ../../Main/WinEditors/Sources
        ../../Main/Shared
        ../../Dlls
)

set_target_properties(Jaded-SDK PROPERTIES FOLDER "Libraries")
