add_library(Jaded-SDK OBJECT
        Sources/Precomp.c
        Sources/Precomp.h
        Sources/projectconfig.h
        Sources/BASe/BAS.c
        Sources/BASe/BAS.h
        Sources/BASe/BASarray.c
        Sources/BASe/BASarray.h
        Sources/BASe/BAScrc.cpp
        Sources/BASe/BAScrc.h
        Sources/BASe/BASlog.c
        Sources/BASe/BASlog.h
        Sources/BASe/BASsys.h
        Sources/BASe/BAStypes.h
        Sources/BASe/BASversion.h
        Sources/BASe/BENch/BENch.h
        Sources/BASe/BENch/BENch_RasterDef.h
        Sources/BASe/CLIbrary/CLIerrid.h
        Sources/BASe/CLIbrary/CLIfile.h
        Sources/BASe/CLIbrary/CLImem.h
        Sources/BASe/CLIbrary/CLIstr.c
        Sources/BASe/CLIbrary/CLIstr.h
        Sources/BASe/CLIbrary/CLIwin.h
        Sources/BASe/CLIbrary/CLIxxx.c
        Sources/BASe/CLIbrary/CLIxxx.h
        Sources/BASe/ERRors/ERR.c
        Sources/BASe/ERRors/ERR.h
        Sources/BASe/ERRors/ERRasser.h
        Sources/BASe/ERRors/ERRdefs.cpp
        Sources/BASe/ERRors/ERRdefs.h
        Sources/BASe/ERRors/ERRstr.h
        Sources/BASe/MEMory/MEM.h
        Sources/BASe/MEMory/MEMdyn.c
        Sources/BASe/MEMory/MEMdynOpt.c
        Sources/BASe/MEMory/MEMLog.c
        Sources/BASe/MEMory/MEMLog.h
        Sources/BASe/MEMory/MEMLogOpt.c
        Sources/BASe/MEMory/MEMpro.c
        Sources/BASe/MEMory/MEMpro.h
        Sources/BASe/MEMory/MEMproOpt.c
        #Sources/BASe/XBox/XBCompositeFile.c
        #Sources/BASe/XBox/XBCompositeFile.h
        Sources/BIGfiles/BIG.c
        Sources/BIGfiles/BIG.h
        Sources/BIGfiles/BIGcheck.c
        Sources/BIGfiles/BIGcheck.h
        Sources/BIGfiles/BIGchecksum.c
        Sources/BIGfiles/BIGchecksum.h
        Sources/BIGfiles/BIGcomp.c
        Sources/BIGfiles/BIGcomp.h
        Sources/BIGfiles/BIGdefs.c
        Sources/BIGfiles/BIGdefs.h
        Sources/BIGfiles/BIGerrid.h
        Sources/BIGfiles/BIGexport.c
        Sources/BIGfiles/BIGexport.h
        Sources/BIGfiles/BIGfat.c
        Sources/BIGfiles/BIGfat.h
        Sources/BIGfiles/BIGgroup.c
        Sources/BIGfiles/BIGgroup.h
        Sources/BIGfiles/BIGio.c
        Sources/BIGfiles/BIGio.h
        Sources/BIGfiles/BIGkey.c
        Sources/BIGfiles/BIGkey.h
        Sources/BIGfiles/BIGmdfy_dir.c
        Sources/BIGfiles/BIGmdfy_dir.h
        Sources/BIGfiles/BIGmdfy_file.c
        Sources/BIGfiles/BIGmdfy_file.h
        Sources/BIGfiles/BIGmerge.c
        Sources/BIGfiles/BIGmerge.h
        Sources/BIGfiles/BIGopen.c
        Sources/BIGfiles/BIGopen.h
        Sources/BIGfiles/BIGread.c
        Sources/BIGfiles/BIGread.h
        Sources/BIGfiles/BIGspecial.c
        Sources/BIGfiles/BIGspecial.h
        Sources/BIGfiles/lzoconf.h
        Sources/BIGfiles/minilzo.c
        Sources/BIGfiles/minilzo.h
        Sources/BIGfiles/IMPort/IMPbase.c
        Sources/BIGfiles/IMPort/IMPbase.h
        Sources/BIGfiles/LOAding/LOA.c
        Sources/BIGfiles/LOAding/LOA.h
        Sources/BIGfiles/LOAding/LOAdefs.c
        Sources/BIGfiles/LOAding/LOAdefs.h
        Sources/BIGfiles/LOAding/LOAerrid.h
        Sources/BIGfiles/LOAding/LOAread.c
        Sources/BIGfiles/LOAding/LOAread.h
        Sources/BIGfiles/SAVing/SAVdefs.c
        Sources/BIGfiles/SAVing/SAVdefs.h
        Sources/BIGfiles/STReams/STReamaccess.cpp
        Sources/BIGfiles/STReams/STReamaccess.h
        Sources/BIGfiles/STReams/STReamBigFile.cpp
        Sources/BIGfiles/STReams/STReamBigFile.h
        Sources/BIGfiles/VERsion/VERsion_Check.cpp
        Sources/BIGfiles/VERsion/VERsion_Check.h
        Sources/BIGfiles/VERsion/VERsion_Number.h
        Sources/BIGfiles/VERsion/VERsion_Update.cpp
        Sources/BIGfiles/VERsion/VERsion_Update.h
        Sources/BIGfiles/VERsion/VERsion_Update10.cpp
        Sources/BIGfiles/VERsion/VERsion_Update11.cpp
        Sources/BIGfiles/VERsion/VERsion_Update12.cpp
        Sources/BIGfiles/VERsion/VERsion_Update13.cpp
        Sources/BIGfiles/VERsion/VERsion_Update14.cpp
        Sources/BIGfiles/VERsion/VERsion_Update15.cpp
        Sources/BIGfiles/VERsion/VERsion_Update16.cpp
        Sources/BIGfiles/VERsion/VERsion_Update17.cpp
        Sources/BIGfiles/VERsion/VERsion_Update18.cpp
        Sources/BIGfiles/VERsion/VERsion_Update19.cpp
        Sources/BIGfiles/VERsion/VERsion_Update2.cpp
        Sources/BIGfiles/VERsion/VERsion_Update20.cpp
        Sources/BIGfiles/VERsion/VERsion_Update21.cpp
        Sources/BIGfiles/VERsion/VERsion_Update22.cpp
        Sources/BIGfiles/VERsion/VERsion_Update23.cpp
        Sources/BIGfiles/VERsion/VERsion_Update24.cpp
        Sources/BIGfiles/VERsion/VERsion_Update25.cpp
        Sources/BIGfiles/VERsion/VERsion_Update26.cpp
        Sources/BIGfiles/VERsion/VERsion_Update27.cpp
        Sources/BIGfiles/VERsion/VERsion_Update28.cpp
        Sources/BIGfiles/VERsion/VERsion_Update29.cpp
        Sources/BIGfiles/VERsion/VERsion_Update3.cpp
        Sources/BIGfiles/VERsion/VERsion_Update30.cpp
        Sources/BIGfiles/VERsion/VERsion_Update31.cpp
        Sources/BIGfiles/VERsion/VERsion_Update32.cpp
        Sources/BIGfiles/VERsion/VERsion_Update33.cpp
        Sources/BIGfiles/VERsion/VERsion_Update34.cpp
        Sources/BIGfiles/VERsion/VERsion_Update35.cpp
        Sources/BIGfiles/VERsion/VERsion_Update36.cpp
        Sources/BIGfiles/VERsion/VERsion_Update4.cpp
        Sources/BIGfiles/VERsion/VERsion_Update5.cpp
        Sources/BIGfiles/VERsion/VERsion_Update6.cpp
        Sources/BIGfiles/VERsion/VERsion_Update7.cpp
        Sources/BIGfiles/VERsion/VERsion_Update8.cpp
        Sources/BIGfiles/VERsion/VERsion_Update9.cpp
        #Sources/BIGfiles/Xbox/xboxStreamingEmul.c
        #Sources/BIGfiles/Xbox/xboxStreamingEmul.h
        #Sources/GameCube/GC_aramheap.c
        #Sources/GameCube/GC_aramheap.h
        #Sources/GameCube/GC_arammng.c
        #Sources/GameCube/GC_arammng.h
        #Sources/GameCube/GC_File.c
        #Sources/GameCube/GC_File.h
        #Sources/GameCube/GC_Stream.h
        Sources/INOut/INO.c
        Sources/INOut/INO.h
        Sources/INOut/INOfile.c
        Sources/INOut/INOfile.h
        Sources/INOut/INOjoystick.c
        Sources/INOut/INOjoystick.h
        Sources/INOut/INOkeyboard.c
        Sources/INOut/INOkeyboard.h
        Sources/INOut/INOlang.c
        Sources/INOut/INOsaving.c
        Sources/INOut/INOsaving.h
        Sources/INOut/INOstruct.h
        #Sources/INOut/gc/gcINOsaving.c
        #Sources/INOut/gc/gcINOsaving.h
        #Sources/INOut/ps2/ps2INOsaving.c
        #Sources/INOut/ps2/ps2INOsaving.h
        Sources/INOut/win32/win32INOsaving.c
        Sources/INOut/win32/win32INOsaving.h
        #Sources/INOut/xbox/xbINOsaving.c
        #Sources/INOut/xbox/xbINOsaving.h
        #Sources/INOut/xenon/sg.png
        #Sources/INOut/xenon/XeINOjoystick.c
        #Sources/INOut/xenon/XeINOjoystick.h
        #Sources/INOut/xenon/XeINOsaving.c
        #Sources/INOut/xenon/XeINOsaving.h
        Sources/IOP/CDV_Manager.h
        Sources/IOP/RPC_Manager.h
        #Sources/IOP/ee/eeCDV_Manager.c
        #Sources/IOP/ee/eeCDV_Manager.h
        #Sources/IOP/ee/eeDebug.h
        #Sources/IOP/ee/eeIOP_RamManager.c
        #Sources/IOP/ee/eeIOP_RamManager.h
        #Sources/IOP/ee/eekernel.h
        #Sources/IOP/ee/eeRPC_Debug.c
        #Sources/IOP/ee/eeRPC_Debug.h
        #Sources/IOP/ee/eeRPC_Manager.c
        #Sources/IOP/ee/eeRPC_Manager.h
        Sources/IOP/iop/iopBAStypes.h
        Sources/IOP/iop/iopCDV_Manager.c
        Sources/IOP/iop/iopCDV_Manager.h
        Sources/IOP/iop/iopCLI.c
        Sources/IOP/iop/iopCLI.h
        Sources/IOP/iop/iopDebug.c
        Sources/IOP/iop/iopDebug.h
        Sources/IOP/iop/iopKernel.h
        Sources/IOP/iop/iopMain.c
        Sources/IOP/iop/iopMain.h
        Sources/IOP/iop/iopMEM.c
        Sources/IOP/iop/iopMEM.h
        Sources/IOP/iop/iopMTX.c
        Sources/IOP/iop/iopMTX.h
        Sources/IOP/iop/iopSND.c
        Sources/IOP/iop/iopSND.h
        Sources/IOP/iop/iopSND_Debug.c
        Sources/IOP/iop/iopSND_Debug.h
        Sources/IOP/iop/iopSND_DmaScheduler.c
        Sources/IOP/iop/iopSND_DmaScheduler.h
        Sources/IOP/iop/iopSND_Fx.c
        Sources/IOP/iop/iopSND_Fx.h
        Sources/IOP/iop/iopSND_Hard.c
        Sources/IOP/iop/iopSND_Hard.h
        Sources/IOP/iop/iopSND_libsd.h
        #Sources/IOP/iop/iopSND_Stream.c
        #Sources/IOP/iop/iopSND_Stream.h
        Sources/IOP/iop/iopSND_Voice.c
        Sources/IOP/iop/iopSND_Voice.h
        Sources/LINks/LINK.cpp
        Sources/LINks/LINK.h
        Sources/LINks/LINKmsg.cpp
        Sources/LINks/LINKmsg.h
        Sources/LINks/LINKstruct.cpp
        Sources/LINks/LINKstruct.h
        Sources/LINks/LINKstruct_reg.cpp
        Sources/LINks/LINKstruct_reg.h
        Sources/LINks/LINKtoed.cpp
        Sources/LINks/LINKtoed.h
        Sources/MATHs/MATH.c
        Sources/MATHs/MATH.h
        Sources/MATHs/MATHasm.h
        Sources/MATHs/MATHconst.h
        Sources/MATHs/MATHdebug.c
        Sources/MATHs/MATHdebug.h
        Sources/MATHs/MATHextern.h
        Sources/MATHs/MATHfloat.h
        Sources/MATHs/MATHinit.c
        Sources/MATHs/MATHinit.h
        Sources/MATHs/MATHlong.h
        Sources/MATHs/MATHmatrix.h
        Sources/MATHs/MATHmatrixAdvanced.c
        Sources/MATHs/MATHmatrixAdvanced.h
        Sources/MATHs/MATHmatrixBase.c
        Sources/MATHs/MATHmatrixBase.h
        Sources/MATHs/MATHmatrixRot.c
        Sources/MATHs/MATHmatrixRot.h
        Sources/MATHs/MATHmatrixScale.c
        Sources/MATHs/MATHmatrixScale.h
        Sources/MATHs/MATHmatrixTrans.h
        Sources/MATHs/MATHmatrixTransform.c
        Sources/MATHs/MATHmatrixTransform.h
        Sources/MATHs/MATHquat.h
        Sources/MATHs/MATHstruct.h
        Sources/MATHs/MATHvars.c
        Sources/MATHs/MATHvars.h
        Sources/MATHs/MATHvector.h
        Sources/MATHs/MATHvector_ALIGNED.h
        Sources/MATHs/MATH_MEM.c
        Sources/MATHs/MATH_MEM.h
        #Sources/MATHs/GC/GCMATHfloat.h
        #Sources/MATHs/GC/GCMATHgector.h
        #Sources/MATHs/GC/GCMATHmatrix.h
        #Sources/MATHs/GC/GCMATHmatrixTransform.c
        #Sources/MATHs/GC/GCMATHvector.h
        Sources/MATHs/ix86/ix86MATHfloat.h
        #Sources/MATHs/PS2/ps2MATHfloat.h
        #Sources/MATHs/PS2/ps2MATHmatrixBase.h
        #Sources/MATHs/PS2/ps2MATHmatrixTransform.c
        #Sources/MATHs/PS2/ps2MATHmatrixTransform_s.s
        #Sources/MATHs/PS2/ps2MATHopt.h
        #Sources/MATHs/PS2/ps2MATHopt_c.c
        #Sources/MATHs/PS2/ps2MATHopt_dsm.dsm
        #Sources/MATHs/PS2/ps2MATHopt_s.s
        #Sources/MATHs/PS2/ps2MATHopt_vsm.vsm
        #Sources/MATHs/PS2/ps2MATHvector.c
        #Sources/MATHs/PS2/ps2MATHvector.h
        #Sources/MATHs/PS2/ps2MATHvector_ALIGNED.h
        #Sources/MATHs/PS2/vumacros.h
        #Sources/MATHs/Xenon/xeMATHfloat.h
        Sources/MC/MC_Manager.c
        Sources/MC/MC_Manager.h
        Sources/package/PackagePak.cpp
        Sources/package/PackagePak.h
        Sources/Random/PerlinNoise.c
        #Sources/Random/PerlinNoise.cpp
        Sources/Random/PerlinNoise.h
        Sources/Random/random.h
        Sources/TABles/TABles.c
        Sources/TABles/TABles.h
        Sources/TABles/TABvars.c
        Sources/TABles/TABvars.h
        Sources/TIMer/TIM.c
        Sources/TIMer/TIM.h
        Sources/TIMer/TIMdefs.c
        Sources/TIMer/TIMdefs.h
        Sources/TIMer/PROfiler/PRO.c
        Sources/TIMer/PROfiler/PRO.h
        Sources/TIMer/PROfiler/PROdefs.c
        Sources/TIMer/PROfiler/PROdefs.h
        Sources/TIMer/PROfiler/PROdisplay.c
        Sources/TIMer/PROfiler/PROdisplay.h
        Sources/TIMer/PROfiler/PROPS2.c
        Sources/TIMer/PROfiler/PROPS2.h
        Sources/TIMer/PROfiler/PROPS2_def.h
        #Sources/TIMer/PROfiler/xbox/font.xpr
        #Sources/TIMer/PROfiler/xbox/PerfTest.cpp
        #Sources/TIMer/PROfiler/xbox/PRO_xb.h
        #Sources/TIMer/PROfiler/xbox/xbapp.h
        #Sources/TIMer/PROfiler/xbox/XbFont.Cpp
        #Sources/TIMer/PROfiler/xbox/XbFont.h
        #Sources/TIMer/PROfiler/xbox/xbinput.h
        #Sources/TIMer/PROfiler/xbox/XBInterface.Cpp
        #Sources/TIMer/PROfiler/xbox/XbResource.Cpp
        #Sources/TIMer/PROfiler/xbox/XbResource.h
        #Sources/TIMer/PROfiler/xbox/XbUtil.Cpp
        #Sources/TIMer/PROfiler/xbox/XbUtil.h
)

target_include_directories(Jaded-SDK
        PUBLIC
        Sources

        PRIVATE
        #TODO: clean this up
        ../../Extern/ode/include
        ../../Extern/sdl3/include
        ../../Main/WinEditors/Sources
        ../../Main/Shared
        ../../Dlls
)

set_target_properties(Jaded-SDK PROPERTIES FOLDER "Libraries")
