add_library(Jaded-Gfx OBJECT
        Sources/Precomp.c
        Sources/Precomp.h

        Sources/CAMera/CAMera.c
        Sources/CAMera/CAMera.h
        Sources/CAMera/CAMstruct.c
        Sources/CAMera/CAMstruct.h
        Sources/GDInterface/GDInterface.c
        Sources/GDInterface/GDInterface.h
        Sources/GDInterface/GDIrasters.c
        Sources/GDInterface/GDIrasters.h
        Sources/GDInterface/GDIrequest.h
        Sources/GDInterface/GDIresolution.c
        Sources/GDInterface/GDIresolution.h
        Sources/GEOmetric/GEOboundingvolume.c
        Sources/GEOmetric/GEOboundingvolume.h
        Sources/GEOmetric/GEOcreateobject.c
        Sources/GEOmetric/GEOcreateobject.h
        Sources/GEOmetric/GEODebugObject.c
        Sources/GEOmetric/GEODebugObject.h
        Sources/GEOmetric/GEOdebugobjectdef.h
        Sources/GEOmetric/GEOload.c
        Sources/GEOmetric/GEOload.h
        #Sources/GEOmetric/GEOmodifier.c
        #Sources/GEOmetric/GEOmodifier.h
        Sources/GEOmetric/GEOobject.c
        Sources/GEOmetric/GEOobject.h
        Sources/GEOmetric/GEOobjectaccess.c
        Sources/GEOmetric/GEOobjectaccess.h
        Sources/GEOmetric/GEOobjectcomputing.c
        Sources/GEOmetric/GEOobjectcomputing.h
        #Sources/GEOmetric/GEOstaticLOD.c
        #Sources/GEOmetric/GEOstaticLOD.h
        #Sources/GEOmetric/GEOstatistics.c
        #Sources/GEOmetric/GEOstatistics.h
        Sources/GEOmetric/GEOsubobject.c
        Sources/GEOmetric/GEOsubobject.h
        Sources/GEOmetric/GEOXenonPack.cpp
        Sources/GEOmetric/GEOXenonPack.h
        Sources/GEOmetric/GEOzone.c
        Sources/GEOmetric/GEOzone.h
        Sources/GEOmetric/GEO_LIGHTCUT.c
        Sources/GEOmetric/GEO_LIGHTCUT.h
        Sources/GEOmetric/GEO_LIGHTCUT_BRONX.c
        Sources/GEOmetric/GEO_LIGHTCUT_DEF.c
        Sources/GEOmetric/GEO_LIGHTCUT_DRAW.c
        Sources/GEOmetric/GEO_LIGHTCUT_FE.c
        Sources/GEOmetric/GEO_LIGHTCUT_GEO.c
        Sources/GEOmetric/GEO_LIGHTCUT_OK3.c
        Sources/GEOmetric/GEO_LIGHTCUT_OPT.c
        Sources/GEOmetric/GEO_LIGHTCUT_RADIO.c
        Sources/GEOmetric/GEO_LIGHTCUT_RT.c
        Sources/GEOmetric/GEO_LIGHTCUT_TOOLS.c
        Sources/GEOmetric/GEO_LODCmpt.c
        Sources/GEOmetric/GEO_LODCmpt.h
        Sources/GEOmetric/GEO_MRM.c
        Sources/GEOmetric/GEO_MRM.h
        Sources/GEOmetric/GEO_SKIN.c
        Sources/GEOmetric/GEO_SKIN.h
        Sources/GEOmetric/GEO_STRIP.c
        Sources/GEOmetric/GEO_STRIP.h
        #Sources/GEOmetric/SCD_MTH.c
        Sources/GFX/GFX.c
        Sources/GFX/GFX.h
        Sources/GFX/GFXcarte.c
        Sources/GFX/GFXcarte.h
        Sources/GFX/GFXdesintegrate.c
        Sources/GFX/GFXdesintegrate.h
        Sources/GFX/GFXExplode.c
        Sources/GFX/GFXExplode.h
        Sources/GFX/GFXfade.c
        Sources/GFX/GFXfade.h
        Sources/GFX/GFXflare.c
        Sources/GFX/GFXflare.h
        Sources/GFX/GFXlightning.c
        Sources/GFX/GFXlightning.h
        Sources/GFX/GFXline.c
        Sources/GFX/GFXline.h
        Sources/GFX/GFXProfiler.c
        Sources/GFX/GFXProfiler.h
        Sources/GFX/GFXripple.c
        Sources/GFX/GFXripple.h
        Sources/GFX/GFXsmoke.c
        Sources/GFX/GFXsmoke.h
        Sources/GFX/GFXspark.c
        Sources/GFX/GFXspark.h
        Sources/GFX/GFXspeed.c
        Sources/GFX/GFXspeed.h
        Sources/GFX/GFXString.c
        Sources/GFX/GFXstring.h
        Sources/GFX/GFXtable.c
        Sources/GFX/GFXtable.h
        Sources/GFX/GFXwater.c
        Sources/GFX/GFXwater.h
        Sources/GRObject/GROedit.h
        Sources/GRObject/GROimportfrommad.c
        Sources/GRObject/GROimportfrommad.h
        Sources/GRObject/GROmemstats.c
        Sources/GRObject/GROmemstats.h
        Sources/GRObject/GROrender.c
        Sources/GRObject/GROrender.h
        Sources/GRObject/GROsave.c
        Sources/GRObject/GROsave.h
        Sources/GRObject/GROstruct.c
        Sources/GRObject/GROstruct.h
        Sources/LIGHT/LIGHTcolor.c
        Sources/LIGHT/LIGHTcompute.c
        Sources/LIGHT/LIGHTmap.c
        Sources/LIGHT/LIGHTmap.h
        Sources/LIGHT/LIGHTmapcompute.c
        Sources/LIGHT/LIGHTmapcompute.h
        Sources/LIGHT/LIGHTmapstruct.h
        #Sources/LIGHT/LIGHTrejection.cpp
        #Sources/LIGHT/LIGHTrejection.h
        Sources/LIGHT/LIGHTstruct.c
        Sources/LIGHT/LIGHTstruct.h
        Sources/MATerial/MATCompute.c
        Sources/MATerial/MATCompute.h
        Sources/MATerial/MATDraw.c
        Sources/MATerial/MATmulti.c
        Sources/MATerial/MATmulti.h
        Sources/MATerial/MATmultitexture.c
        Sources/MATerial/MATmultitexture.h
        Sources/MATerial/MATShadow.c
        Sources/MATerial/MATShadow.h
        Sources/MATerial/MATSingle.c
        Sources/MATerial/MATSingle.h
        Sources/MATerial/MATSprite.c
        Sources/MATerial/MATSprite.h
        Sources/MATerial/MATSprite_Load.c
        Sources/MATerial/MATstruct.c
        Sources/MATerial/MATstruct.h
        #Sources/MATerial/PCretail/MATCompute.c
        #Sources/MATerial/xbox/MATCompute.c
        #Sources/MATerial/xbox/MATDraw.c
        #Sources/MATerial/xbox/MATShadow.c
        #Sources/MATerial/xbox/MATSprite.c
        Sources/PArticleGenerator/PAGstruct.c
        Sources/PArticleGenerator/PAGstruct.h
        Sources/SELection/SELection.c
        Sources/SELection/SELection.h
        Sources/SOFT/SOFTbackgroundimage.c
        Sources/SOFT/SOFTbackgroundimage.h
        Sources/SOFT/SOFTcolor.c
        Sources/SOFT/SOFTcolor.h
        Sources/SOFT/SOFTHelper.h
        Sources/SOFT/SOFTHelpers.c
        Sources/SOFT/SOFTlinear.c
        Sources/SOFT/SOFTlinear.h
        Sources/SOFT/SOFTMatrixStack.c
        Sources/SOFT/SOFTMatrixStack.h
        Sources/SOFT/SOFTPickingBuffer.c
        Sources/SOFT/SOFTPickingBuffer.h
        Sources/SOFT/SOFTstrings.h
        Sources/SOFT/SOFTstruct.h
        Sources/SOFT/SOFTuvgizmo.c
        Sources/SOFT/SOFTUVGizmo.h
        Sources/SOFT/SOFTWebCam.cpp
        Sources/SOFT/SOFTzlist.c
        Sources/SOFT/SOFTzlist.h
        Sources/STRing/STRaccess.c
        Sources/STRing/STRdata.c
        Sources/STRing/STRdata.h
        Sources/STRing/STReffects.c
        Sources/STRing/STRfont.c
        Sources/STRing/STRparse.c
        Sources/STRing/STRrender.c
        Sources/STRing/STRstruct.c
        Sources/STRing/STRstruct.h
        Sources/TEXture/stb_image.h
        Sources/TEXture/TEXani.c
        Sources/TEXture/TEXani.h
        Sources/TEXture/TEXanimated.c
        Sources/TEXture/TEXanimated.h
        Sources/TEXture/TEXconvert.c
        Sources/TEXture/TEXconvert.h
        Sources/TEXture/TEXcubemap.c
        Sources/TEXture/TEXcubemap.h
        Sources/TEXture/TEXeditorfct.c
        Sources/TEXture/TEXeditorfct.h
        Sources/TEXture/TEXfile.c
        Sources/TEXture/TEXfile.h
        Sources/TEXture/TEXhardwareload.c
        Sources/TEXture/TEXhardwareload.h
        Sources/TEXture/TEXlist.c
        Sources/TEXture/TEXmanager.c
        Sources/TEXture/TEXmanager.h
        Sources/TEXture/TEXmemory.c
        Sources/TEXture/TEXmemory.h
        Sources/TEXture/TEXprocedural.c
        Sources/TEXture/TEXprocedural.h
        Sources/TEXture/TEXstruct.h
        Sources/TEXture/TEXxenon.cpp
        Sources/TEXture/TEXxenon.h
        Sources/TEXture/TEX_Bink.c
        Sources/TEXture/TEX_Bink.h
        Sources/TEXture/TEX_mesh.c
        Sources/TEXture/TEX_mesh.h
        Sources/TEXture/TEX_mesh_internal.h
        #Sources/TEXture/TEX_mesh_x86.c
        #Sources/TEXture/TEX_Sub.c
        Sources/TEXture/Water_FFT.c
        Sources/TEXture/Water_FFT.h
        Sources/WAYpoint/WAYlink.c
        Sources/WAYpoint/WAYlink.h
        Sources/WAYpoint/WAYpoint.c
        Sources/WAYpoint/WAYpoint.h

        #Sources/backends/dx9/DX9blending.c
        #Sources/backends/dx9/DX9blending.h
        #Sources/backends/dx9/DX9buffer.c
        #Sources/backends/dx9/DX9buffer.h
        #Sources/backends/dx9/DX9console.c
        #Sources/backends/dx9/DX9console.h
        #Sources/backends/dx9/DX9draw.c
        #Sources/backends/dx9/DX9draw.h
        #Sources/backends/dx9/DX9gauges.c
        #Sources/backends/dx9/DX9gauges.h
        #Sources/backends/dx9/DX9init.c
        #Sources/backends/dx9/DX9init.h
        #Sources/backends/dx9/DX9matrix.c
        #Sources/backends/dx9/DX9matrix.h
        #Sources/backends/dx9/DX9renderstate.c
        #Sources/backends/dx9/DX9renderstate.h
        #Sources/backends/dx9/DX9request.c
        #Sources/backends/dx9/DX9request.h
        #Sources/backends/dx9/DX9samplerstate.c
        #Sources/backends/dx9/DX9samplerstate.h
        #Sources/backends/dx9/DX9struct.h
        #Sources/backends/dx9/DX9tex.c
        #Sources/backends/dx9/DX9tex.h
        #Sources/backends/dx9/DX9texturestagestate.c
        #Sources/backends/dx9/DX9texturestagestate.h
        #Sources/backends/dx9/DX9uv.h

        Sources/backends/gl/OGLAfterEffects.cpp
        Sources/backends/gl/OGLAfterEffects.h
        Sources/backends/gl/OGLCloneDraw.cpp
        Sources/backends/gl/OGLdebugfct.cpp
        Sources/backends/gl/OGLdebugfct.h
        Sources/backends/gl/OGLinit.cpp
        Sources/backends/gl/OGLinit.h
        Sources/backends/gl/OGLOcclusion.cpp
        Sources/backends/gl/OGLrenderstate.cpp
        Sources/backends/gl/OGLrenderstate.h
        Sources/backends/gl/OGLrequest.cpp
        Sources/backends/gl/OGLrequest.h
        Sources/backends/gl/OGLShiftDraw.cpp
        Sources/backends/gl/OGLStringDraw.cpp
        Sources/backends/gl/OGLtex.cpp
        Sources/backends/gl/OGLtex.h
        Sources/backends/gl/OGLWater.cpp
        Sources/backends/gl/OGLWater.h
        Sources/backends/gl/Precomp.cpp
        Sources/backends/gl/Precomp.h
        Sources/backends/gl/ShaderManager.cpp
)

target_include_directories(Jaded-Gfx
        PUBLIC
        Sources

        PRIVATE
        #TODO: clean this up
        ../../Extern/glew/include
        ../../Extern/ode/include
        ../../Extern/sdl3/include
        ../../Main/WinEditors/Sources
        ../../Dlls
)

target_link_libraries(Jaded-Gfx Jaded-SDK Jaded-Engine)
set_target_properties(Jaded-Gfx PROPERTIES FOLDER "Libraries")
