/*
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    !! This file is generated by Jade editor !!
    INOlang.c : 2005/6/26 - 20:49
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*/


#include "Precomp.h"
#include "INO.h"

int INO_gai_PresentLanguage[INO_e_MaxLangNb] =
{
 1, /* French */
 1, /* English */
 1, /* Danish */
 1, /* Dutch */
 1, /* Finnish */
 1, /* German */
 1, /* Italian */
 1, /* Spanish */
 0, /* Portuguese */
 1, /* Swedish */
 0, /* Polish */
 0, /* Russian */
 0, /* Japanese */
 0, /* Chinese */
 0, /* Albanian */
 0, /* Arabic */
 0, /* Bulgarian */
 0, /* Byelorussian */
 0, /* Greek */
 0, /* Korean */
 1, /* Norwegian */
 0, /* Romanian */
 0, /* Serbian */
 0, /* Slovak */
 0, /* Slovenian */
 0, /* Turkish */
 0, /* Czech */
 0, /* Hungarian */
 0  /* Taiwanese */
};

/*
 ***********************************************************************************************************************
    EOF
 ***********************************************************************************************************************
*/
