add_library(Jaded-AI OBJECT
    Sources/AI.c
    Sources/AI.h
    Sources/AI2C.cpp
    Sources/AI2C_fctdefs.h
    Sources/AI2C_fctheader.h
    Sources/AI2C_fctlist.h
    #Sources/AI2C_fctlist0.cpp
    #Sources/AI2C_fctlist1.cpp
    #Sources/AI2C_fctlist2.cpp
    #Sources/AI2C_fctlist3.cpp
    #Sources/AI2C_fctlist4.cpp
    #Sources/AI2C_fctlist5.cpp
    #Sources/AI2C_fctlist6.cpp
    #Sources/AI2C_fctlist7.cpp
    #Sources/AI2C_fctlist8.cpp
    #Sources/AI2C_fctlist9.cpp
    Sources/AI2C_mdlheader.h
    Sources/AIBench.c
    Sources/AIBench.h
    Sources/AIdebug.c
    Sources/AIdebug.h
    Sources/AIengine.c
    Sources/AIengine.h
    Sources/AIerrid.h
    Sources/AIload.c
    Sources/AIload.h
    Sources/AImsg.h
    Sources/AIsave.c
    Sources/AIsave.h
    Sources/AIstack.h
    Sources/AIstruct.h
    Sources/AItools.h
    Sources/Precomp.c
    Sources/Precomp.h
    #Sources/AI2C_dll/AI2C_CrossReference.c
    #Sources/AI2C_dll/AI2C_CrossReference.h
    Sources/AI2C_dll/AI2C_dll.c
    #Sources/AI2C_dll/AI2C_FixFct.cpp
    #Sources/AI2C_dll/AIdll000.cpp
    #Sources/AI2C_dll/AIdll001.cpp
    #Sources/AI2C_dll/AIdll002.cpp
    #Sources/AI2C_dll/AIdll003.cpp
    #Sources/AI2C_dll/AIdll004.cpp
    #Sources/AI2C_dll/AIdll005.cpp
    #Sources/AI2C_dll/AIdll006.cpp
    #Sources/AI2C_dll/AIdll007.cpp
    #Sources/AI2C_dll/AIdll008.cpp
    #Sources/AI2C_dll/AIdll009.cpp
    #Sources/AI2C_dll/AIdll010.cpp
    #Sources/AI2C_dll/AIdll011.cpp
    #Sources/AI2C_dll/AIdll012.cpp
    #Sources/AI2C_dll/AIdll013.cpp
    #Sources/AI2C_dll/AIdll014.cpp
    #Sources/AI2C_dll/AIdll015.cpp
    #Sources/AI2C_dll/AIdll016.cpp
    #Sources/AI2C_dll/AIdll017.cpp
    #Sources/AI2C_dll/AIdll018.cpp
    #Sources/AI2C_dll/AIdll019.cpp
    #Sources/AI2C_dll/AIdll020.cpp
    #Sources/AI2C_dll/AIdll021.cpp
    #Sources/AI2C_dll/AIdll022.cpp
    #Sources/AI2C_dll/AIdll023.cpp
    #Sources/AI2C_dll/AIdll024.cpp
    #Sources/AI2C_dll/AIdll025.cpp
    #Sources/AI2C_dll/AIdll026.cpp
    #Sources/AI2C_dll/AIdll027.cpp
    #Sources/AI2C_dll/AIdll028.cpp
    #Sources/AI2C_dll/AIdll029.cpp
    #Sources/AI2C_dll/AIdll030.cpp
    #Sources/AI2C_dll/AIdll031.cpp
    #Sources/AI2C_dll/AIdll032.cpp
    #Sources/AI2C_dll/AIdll033.cpp
    #Sources/AI2C_dll/AIdll034.cpp
    #Sources/AI2C_dll/AIdll035.cpp
    #Sources/AI2C_dll/AIdll036.cpp
    #Sources/AI2C_dll/AIdll037.cpp
    #Sources/AI2C_dll/AIdll038.cpp
    #Sources/AI2C_dll/AIdll039.cpp
    #Sources/AI2C_dll/AIdll040.cpp
    #Sources/AI2C_dll/AIdll041.cpp
    #Sources/AI2C_dll/AIdll042.cpp
    #Sources/AI2C_dll/AIdll043.cpp
    #Sources/AI2C_dll/AIdll044.cpp
    #Sources/AI2C_dll/AIdll045.cpp
    #Sources/AI2C_dll/AIdll046.cpp
    #Sources/AI2C_dll/AIdll047.cpp
    #Sources/AI2C_dll/AIdll048.cpp
    #Sources/AI2C_dll/AIdll049.cpp
    #Sources/AI2C_dll/AIdll050.cpp
    #Sources/AI2C_ofc/CINE_PlayVIDEO.cpp
    #Sources/AI2C_ofc/CINE_PlayVIDEO.h
    #Sources/AI2C_ofc/rayman.h
    Sources/Categs/AIcateg.c
    Sources/Categs/AIdefcateg.h
    Sources/Events/EVEconst.h
    Sources/Events/EVEinit.c
    Sources/Events/EVEinit.h
    Sources/Events/EVEload.c
    Sources/Events/EVEload.h
    Sources/Events/EVEnt_aifunc.c
    Sources/Events/EVEnt_aifunc.h
    Sources/Events/EVEnt_interpolationkey.c
    Sources/Events/EVEnt_interpolationkey.h
    Sources/Events/EVEnt_morphkey.c
    Sources/Events/EVEnt_morphkey.h
    #Sources/Events/EVEnt_timekey.c
    #Sources/Events/EVEnt_timekey.h
    Sources/Events/EVEplay.c
    Sources/Events/EVEplay.h
    Sources/Events/EVEsave.c
    Sources/Events/EVEsave.h
    Sources/Events/EVEstruct.h
    Sources/Fields/AIdeffields.h
    Sources/Fields/AIfields.c
    Sources/Functions/AIdeffct.h
    Sources/Functions/AIfunctions_action.c
    Sources/Functions/AIfunctions_ai.c
    Sources/Functions/AIfunctions_ani.c
    Sources/Functions/AIfunctions_arr.c
    Sources/Functions/AIfunctions_cam.c
    Sources/Functions/AIfunctions_cam.h
    Sources/Functions/AIfunctions_cast.c
    Sources/Functions/AIfunctions_col.c
    Sources/Functions/AIfunctions_COLOR.c
    Sources/Functions/AIfunctions_dbg.c
    Sources/Functions/AIfunctions_dyn.c
    Sources/Functions/AIfunctions_GFX.c
    Sources/Functions/AIfunctions_grid.c
    Sources/Functions/AIfunctions_io.c
    Sources/Functions/AIfunctions_light.c
    Sources/Functions/AIfunctions_MAT.c
    Sources/Functions/AIfunctions_msg.c
    Sources/Functions/AIfunctions_mth.c
    Sources/Functions/AIfunctions_net.c
    Sources/Functions/AIfunctions_obj.c
    Sources/Functions/AIfunctions_objtext.c
    Sources/Functions/AIfunctions_save.c
    Sources/Functions/AIfunctions_savephotos.c
    Sources/Functions/AIfunctions_savephotos.h
    Sources/Functions/AIfunctions_sct.c
    Sources/Functions/AIfunctions_snd.c
    #Sources/Functions/AIfunctions_softBody.c
    Sources/Functions/AIfunctions_text.c
    Sources/Functions/AIfunctions_time.c
    Sources/Functions/AIfunctions_tra.c
    Sources/Functions/AIfunctions_view.c
    Sources/Functions/AIfunctions_way.c
    Sources/Functions/AIfunctions_wor.c
    #Sources/Functions/AIfunctions_Xenon.c
    Sources/Functions/AIfunctions_XMEN.c
    Sources/Keywords/AIdefkey.h
    Sources/Keywords/AIkeywords.c
    Sources/Types/AIdeftyp.h
    Sources/Types/AItypes.c
)

target_include_directories(Jaded-AI
        PUBLIC
        Sources

        PRIVATE
        #TODO: clean this up
        ../../Extern/ode/include
        #../../Extern/sdl3/include
        ../../Main/WinEditors/Sources
        ../../Dlls
)

target_link_libraries(Jaded-AI Jaded-SDK Jaded-Engine)
