name: Build Debug (Windows MSVC x86)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2.4.0

      - name: 'Setup MSBuild'
        uses: microsoft/setup-msbuild@v2
        with:
          vs-prerelease: false
          msbuild-architecture: "x86"

      - name: Build
        # Build your program with the given configuration
        run: MSBuild /t:JadeShell /property:Configuration="Debug Editors" /property:Platform=Win32 /maxcpucount Main/Jade.sln

      - name: 'Package Release'
        run: zip web/releases/jaded-debug.zip mappings/* changes.txt Jaded.exe run_window.bat run_console.bat run_editor.bat SDL3.dll legal.txt

      - name: 'Upload to Discord'
        uses: tsickert/discord-webhook@v5.3.0
        continue-on-error: true
        with:
          webhook-url: ${{ secrets.DISCORD }}
          filename: web/releases/jaded-debug.zip

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jaded-release
          path: web/releases/jaded-debug.zip
          retention-days: 30
