/*$T EVEmsg.h GC! 1.086 06/27/00 12:30:58 */


/*$6
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */


#pragma once
#include "EDIeditors_infos.h"

#define EEVE_MESSAGE_RECOMPUTE			EDI_MSG_EVE + 0
#define EEVE_MESSAGE_ADDDELCURVEROT		EDI_MSG_EVE + 2
#define EEVE_MESSAGE_ADDDELCURVETRA		EDI_MSG_EVE + 3
#define EEVE_MESSAGE_SHOWTHISCURVEROT	EDI_MSG_EVE + 4
#define EEVE_MESSAGE_SPLITKEY			EDI_MSG_EVE + 10
#define EEVE_MESSAGE_SPLITKEYROT		EDI_MSG_EVE + 11
#define EEVE_MESSAGE_SPLITKEYTRA		EDI_MSG_EVE + 12
#define EEVE_MESSAGE_DELKEY				EDI_MSG_EVE + 20
#define EEVE_MESSAGE_DELKEYROT			EDI_MSG_EVE + 21
#define EEVE_MESSAGE_DELKEYTRA			EDI_MSG_EVE + 22
#define EEVE_MESSAGE_MOVEKEYLEFTROT		EDI_MSG_EVE + 23
#define EEVE_MESSAGE_MOVEKEYRIGHTROT	EDI_MSG_EVE + 24
#define EEVE_MESSAGE_MOVEKEYLEFTTRA		EDI_MSG_EVE + 25
#define EEVE_MESSAGE_MOVEKEYRIGHTTRA	EDI_MSG_EVE + 26
#define EEVE_MESSAGE_MOVEKEYLEFT		EDI_MSG_EVE + 27
#define EEVE_MESSAGE_MOVEKEYRIGHT		EDI_MSG_EVE + 28
#define EEVE_MESSAGE_RECOMPUTEHIE		EDI_MSG_EVE + 30
#define EEVE_MESSAGE_SELECTALLBONES		EDI_MSG_EVE + 31
#define EEVE_MESSAGE_IK					EDI_MSG_EVE + 32
#define EEVE_MESSAGE_SWITCHTRANS		EDI_MSG_EVE + 33
#define EEVE_MESSAGE_FORCEPLAY0			EDI_MSG_EVE + 34

#define EEVE_MESSAGE_COPY				EDI_MSG_EVE + 40
#define EEVE_MESSAGE_PASTE				EDI_MSG_EVE + 41
#define EEVE_MESSAGE_PASTESYMETRYINSERT	EDI_MSG_EVE + 44
#define EEVE_MESSAGE_PASTESYMETRYREF	EDI_MSG_EVE + 45
#define EEVE_MESSAGE_PASTEABSOLUTE		EDI_MSG_EVE + 46

#define EEVE_MESSAGE_TBGENERAL			EDI_MSG_EVE + 50
#define EEVE_MESSAGE_TBPLAY				EDI_MSG_EVE + 51
#define EEVE_MESSAGE_SETFRAME			EDI_MSG_EVE + 52
#define EEVE_MESSAGE_ADDSETFRAME		EDI_MSG_EVE + 53
#define EEVE_MESSAGE_ADDSETFRAME2		EDI_MSG_EVE + 54